// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHsUicdbUaas7RhLac8I7EhN4RiEnlu4',
    appId: '1:952843904069:web:9dd6a0486d9ef1b5802f2c',
    messagingSenderId: '952843904069',
    projectId: 'dep-2-1f180',
    authDomain: 'dep-2-1f180.firebaseapp.com',
    storageBucket: 'dep-2-1f180.appspot.com',
    measurementId: 'G-70WB3511CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyK0sSqxGYULxxtQYuEzbn-7IR1VJ7iQg',
    appId: '1:952843904069:android:42872c00b4ec8d9e802f2c',
    messagingSenderId: '952843904069',
    projectId: 'dep-2-1f180',
    storageBucket: 'dep-2-1f180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfA2V0LVQyGQVRFQ4xLHTq6CvFIJHqtk0',
    appId: '1:952843904069:ios:05a13b4e344f35df802f2c',
    messagingSenderId: '952843904069',
    projectId: 'dep-2-1f180',
    storageBucket: 'dep-2-1f180.appspot.com',
    iosClientId: '952843904069-uvhjfkfui1qvuc7fvve0rcgq3vnl5vlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dep2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfA2V0LVQyGQVRFQ4xLHTq6CvFIJHqtk0',
    appId: '1:952843904069:ios:05a13b4e344f35df802f2c',
    messagingSenderId: '952843904069',
    projectId: 'dep-2-1f180',
    storageBucket: 'dep-2-1f180.appspot.com',
    iosClientId: '952843904069-uvhjfkfui1qvuc7fvve0rcgq3vnl5vlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dep2',
  );
}
